### ISSUE TITLE
Harvesting screen. Add the required balance message

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-mobile-wallet#36]

**Comment by cryptoBeliever** [comment]
@OlegMakarenko 
Message is now "To harvest, the account needs a vested balance of at least 10000 XYM"
I guess this is invalid because there is no vesting in Symbol. 

Maybe we should change to same message as on desktop wallet or just remove "vested"? 
"The account needs to hold at least 10000 XYMs to start delegated harvesting."

**Comment by cryptoBeliever** [comment]
@Peersyst could we update this message?
